### ISSUE TITLE
Calls: removeStrains Execution halted

### ISSUE THREAD

**Issue by stebliankin** [ohlab/SMEG#3]
I have the following error during the "BUILDING SMEG DATABASE(S)" step in _build_sp_

```
Error in data[!rownames(data) %in% outlier, ] : 
  incorrect number of dimensions
Calls: removeStrains
Execution halted
```

The error disappears when I change 
`until [ ! $count -lt 3 ]` to `until [ ! $count -lt 2 ]` in the line 232 of  _build_sp_

For some reason, during the third iteration, the input is corrupted.
Can you please advise what might be the problem? How the setting of less number of iterations going to affect the results?

Thank you!

**Comment by aemiol** [comment]
Hi, using lesser iterations will NOT affect your results. Multiple iteration is conducted to see if more unique SNPs can be generated for clusters. Infact, there is an option to run the build without iteration.

Without seeing the actual data (i.e. strains), it is hard to predict why it failed at the 3rd iteration.

Cheers,
Tunde

**Comment by stebliankin** [comment]
Thank you so much for your quick response and for your great work!
