### ISSUE TITLE
Halted at draft genome re-order step

### ISSUE THREAD

**Issue by fannimi2001** [ohlab/SMEG#4]
I'm trying to build a database for my interesting species with 90 genomes. The building step halted at re-ordering step for more than a week. I'm wondering is that exceeds the computing limit.

**Comment by aemiol** [comment]
That is quite weird. SMEG uses the tool Mauve to reorder genomes. Are all your genomes from the same species? I suspect one or some of your genomes are contaminants. Did you successfully run the example test? Is there a way you can share your genomes so I have a quick look?

- Tunde

**Comment by fannimi2001** [comment]
B_uni_genomes.tgz
<https://drive.google.com/file/d/1N44Yh8eGmmeXrW07YP-14yD_VmOfDXOj/view?usp=drive_web>
Yes, I did successfully run the example test. Please find the genomes
attached.

Mi

**Comment by aemiol** [comment]
The build ran successfully on my system without a hitch. The command used was "smeg build_species -g . -o B_uni -a -p 30" and it took just over 8 hr on the cluster. 

Did you run it on your local machine or on an HPC environment? Anyway, you can download the build results from https://drive.google.com/file/d/1rzKFm-pUBS2P6UGvOJlDdR5-AwVXKQWH/view?usp=sharing

Going through the log file (log.txt), the preferred database will be B_uni/T.0.6/ **or** B_uni/F.0.6/

Cheers,
Tunde

**Comment by fannimi2001** [comment]
Thank you so much!  The command I ever used was "smeg build_species -g . -o
B_uni -a -p 16" on the cluster.

Mi
