### ISSUE TITLE
Example test error: build_species is unable to detect reference genome files

### ISSUE THREAD

**Issue by mhyleung** [ohlab/SMEG#6]
Dear all

After installing SMEG using conda according to the installation step and making sure I have all the dependencies, I was trying to run the example test. I got the following error when trying to run the "build_species" module in the example test:

```bash
 ################ Checking for dependencies ########
gcc found
parallel found
R found
Mauve found
roary found
prokka found
bowtie2 found
samtools found
bamtools found
bedtools found
blastn found
All required packages found
 ################ Checking for required R libraries ########
Output directory ok
R libraries ok
build_species option activated
/home/[user]/smeg/SMEG-1.1.1/test is present directory
/home/[user]/smeg/SMEG-1.1.1/test is the genomes directory
/home/[user]/smeg/SMEG-1.1.1/test/test_database is the output directory
####### PRE PROCESSING GENOMES #####
ERROR: At least, a complete reference genome is required to reorder contigs of draft genomes
```

I notice that there was a previous thread related to this based on user data (https://github.com/ohlab/SMEG/issues/2), but not the test dataset, and I cannot locate the "num_of_contigs.txt" in the example test directory. Am I missing something here? My collection of files in the test folder appears to match with that of https://github.com/ohlab/SMEG/tree/master/test

Thank you very much ~

Marc

**Comment by aemiol** [comment]
Hi Marc, 
It appears the package "rename" is not default on your OS. 
Simply install using "sudo apt-get install -y rename" . 

Let me know if this fixed the issue

Cheers,
Tunde

**Comment by mhyleung** [comment]
Hi Tunde

Thanks for the quick reply!

I got this though:
```bash
sudo apt-get install -y rename
Reading package lists... Done
Building dependency tree       
Reading state information... Done
rename is already the newest version (1.10-1).
The following packages were automatically installed and are no longer required:
  libargon2-1 libcryptsetup12 systemd
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```
And the problem persists.

I haven't removed the libargon2-1 libcryptsetup12 system as I do not think they are the cause of this issue...
Thanks

Marc

**Comment by aemiol** [comment]
Hi Marc,
Are you able to install SMEG on a HPC environment via conda? Alternatively, would it be possible to run SMEG via singularity? 

Cheers,
Tunde

**Comment by mhyleung** [comment]
Hi Tunde

I set up Singularity and the example test works fine. I wonder what the problem is with the conda version though. It seems like I am the only one so far who has encounter this issue with the example test. Perhaps we can have an option to generate a log file of some sort for the next version of SMEG?

In any case, this seems to be a very promising tool to use. I thank you guys for making this available for your help with this!

Regards

Marcus

**Comment by aemiol** [comment]
I'm glad it worked for you and thanks for the feedback.

Cheers,
Tunde
